# Versión del formato del archivo docker-compose
version: '3.8'

# Definición de los servicios (contenedores) que vamos a crear
services:
  # Nuestro servicio de base de datos se llamará 'db'
  db:
    # Usaremos la imagen oficial de PostgreSQL, versión 14
    image: postgres:14
    # Si el contenedor se detiene, queremos que se reinicie automáticamente
    restart: always
    # Variables de entorno para configurar la base de datos
    # ¡IMPORTANTE! Cambia 'tu_contraseña_segura' por una contraseña real y segura.
    environment:
      POSTGRES_USER: terranova_user
      POSTGRES_PASSWORD: 190852Jj@_
      POSTGRES_DB: terranova_db
    # Mapeo de puertos: El puerto 5432 del contenedor se expondrá como el puerto 5432 en tu computadora
    ports:
      - "5432:5432"
    # Volumen de datos: Esto asegura que los datos de tu base de datos no se borren
    # aunque apagues y prendas el contenedor.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Definición de los volúmenes para persistir datos
volumes:
  postgres_data:
  